#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 11, 2018 05:57:58 PM JST  platform: Windows NT

import sys
from wxpy import *
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def denglu():
    global bot
    bot =Bot()
    print('autowx_support.denglu')
    sys.stdout.flush()

def flist():
    all_friends = bot.friends()
    myall = all_friends.search()
    #messagebox.showinfo('好友们',myall)
    for f in myall:
        messagebox.showinfo('好友们', f)
    #print(myall)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import autowx.py
    autowx.py.vp_start_gui()




